apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipelines-test
  namespace: rhde-dev-instance
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
