kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: rhde-dev-instance
  namespace: rhde-dev-instance
  labels:
    app: rhde-dev-instance
    app.kubernetes.io/component: rhde-dev-instance
    app.kubernetes.io/instance: rhde-dev-instance
    app.kubernetes.io/name: rhde-dev-instance
    app.kubernetes.io/part-of: rhde-dev-instance
spec:
  lookupPolicy:
    local: false