apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:openshift:scc:scc-sysadmin
  namespace: rhde-dev-instance
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:scc-sysadmin
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: rhde-dev-instance