apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: scc-sysadmin
allowPrivilegedContainer: true
allowedCapabilities:
- SYS_ADMIN
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny