
# https://www.itix.fr/blog/build-multi-architecture-container-images-with-kubernetes-buildah-tekton-and-qemu/
---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-deploy
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: git-url
      type: string
      description: url of the git repo for the code of deployment
      default: https://github.com/tosin2013/redhat-edge-ai-industrial-demo.git
    - name: IMAGE
      type: string
      description: image to be built from the code
      default: image-registry.openshift-image-registry.svc:5000/rhde-dev-instance/redhat-edge-ai-industrial-demo:latest
    - name: buildahPlatforms
      type: array
      default:
      - linux/x86_64
      - linux/arm64/v8
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.git-url)
        - name: depth
          value: '1'  #
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
    - name: build-image
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: TLSVERIFY
          value: "false"
        - name: IMAGE
          value: $(params.IMAGE)
        - name: CONTEXT
          value: container
        - name: buildahPlatforms  # Adding this to specify the target platforms
          value:
          - $(params.buildahPlatforms[*])
      workspaces:
        - name: source
          workspace: shared-workspace
      runAfter:
        - fetch-repository
    - name: apply-manifests
      taskRef:
        name: apply-manifests
      workspaces:
        - name: source
          workspace: shared-workspace
      runAfter:
        - build-image
