- op: replace
  path: /spec/template/spec/source/repoURL
  value: 'https://github.com/tosin2013/redhat-edge-ai-industrial-demo-infra.git'
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: main
