kind: Deployment
apiVersion: apps/v1
metadata:
  name: rhde-dev-instance
  namespace: rhde-dev-instance
  labels:
    app: rhde-dev-instance
    app.kubernetes.io/component: rhde-dev-instance
    app.kubernetes.io/instance: rhde-dev-instance
    app.kubernetes.io/name: rhde-dev-instance
    app.kubernetes.io/part-of: rhde-dev-instance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rhde-dev-instance
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rhde-dev-instance
        deployment: rhde-dev-instance
    spec:
      containers:
        - name: rhde-dev-instance
          image: >-
            image-registry.openshift-image-registry.svc:5000/rhde-dev-instance/rhde-dev-instance:latest
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
